name: calm_notes
description: "A mental health journaling app."
publish_to: "none"
version: 1.2.1+4

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  another_flutter_splash_screen: ^1.2.1
  auto_size_text: ^3.0.0
  back_button_interceptor: ^7.0.3
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^3.0.1
  go_router: ^14.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  material_symbols_icons: ^4.2771.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Black.ttf
          weight: 800
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 600
  assets:
    - assets/images/
    - assets/translations/
    - assets/lottie/
    - assets/icons/
