name: calm_notes
description: "A mental health journaling app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  easy_localization: ^3.0.7
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.7
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  intl: ^0.19.0
  material_symbols_icons: ^4.2771.0
  modal_bottom_sheet: ^3.0.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Black.ttf
          weight: 800
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 600
  assets:
  - assets/translations/
  - assets/images/mood0.svg
  - assets/images/mood1.svg
  - assets/images/mood2.svg
  - assets/images/mood3.svg
  - assets/images/mood4.svg
  - assets/images/mood5.svg
  - assets/images/mood6.svg
  - assets/images/mood7.svg
  - assets/images/mood8.svg
  - assets/images/mood9.svg
  - assets/images/mood10.svg
